### ISSUE TITLE
Dotadle is broken as of 08/14 (at least)

### ISSUE THREAD

**Issue by sicarionox** [leskaa/dotadle#1]
Basically the title, the site breaks after selecting the first hero, spewing out a lot of console errors. 
<img width="745" alt="image" src="https://github.com/leskaa/dotadle/assets/2202764/56793d30-8c72-4db9-86aa-20909dda778b">

**Comment by leskaa** [comment]
Thanks for the heads up @sicarionox! It looks like we ran out of heroes. 
I'll update the site today with a new set that should last until mid-December.

**Comment by sicarionox** [comment]
awesome! ill be closing this then
