### ISSUE TITLE
Dotadle seems to be broken again

### ISSUE THREAD

**Issue by kadank** [leskaa/dotadle#3]
The site goes blank after the first hero is chosen, outputting lots of errors![Screenshot_20231219_102240_Kiwi Browser.jpg](https://github.com/leskaa/dotadle/assets/102073959/d8a8906e-0553-4a1d-a8b5-e63ff93305c1)

**Comment by sicarionox** [comment]
we ran out of heroes! i was about to send a reminder issue myself 😅

**Comment by kadank** [comment]
The issue was fixed, thank you very much!

**Comment by kadank** [comment]
Closing the issue
